name: Convert and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Create build dir
        run: mkdir build

      - name: Convert Markdown
        uses: docker://pandoc/core:2.9
        with:
          args: --standalone -s Protokoll/PPQ1_Routenplaner.docx -o build/index.md

      - name: Convert HTML
        uses: docker://pandoc/core:2.9
        with:
          args: --standalone -s Protokoll/PPQ1_Routenplaner.docx -o build/index.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: protokoll
          FOLDER: build